import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const SongsPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Songs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main >

      </main>


    </div>
  )
}
export default SongsPage;

export async function getStaticProps(context) {
    const res = await fetch(`https://.../data`)
    const data = await res.json()

    if (!data) {
        return {
            notFound: true,
        }
    }

    return {
        props: { data }, // will be passed to the page component as props
    }
}


