import Head from 'next/head'
import Link from "next/link";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Playlist</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main>

            </main>
            <p>This is the index</p>
            <Link href="/songs">Go to playlist songs</Link>
        </div>
    )
}